source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins

# group :jekyll_plugins do
#   # gem "jekyll-archives"
#   gem "jekyll-feed"
#   gem 'jekyll-sitemap'
#   gem 'hawkins'
# end
